### ISSUE TITLE
Current Angular?

### ISSUE THREAD

**Issue by kylecordes** [angular/angular-bazel-example#288]
It would be great to see this example repo updated to current Angular. I've been pointing people here for a while but have had it pointed back that this is back a couple of versions.

**Comment by manekinekko** [comment]
Right. Thanks for pointing that out.

**Comment by alexeagle** [comment]
Renovate did send the PR to update, but since Angular is currently both in package.json and WORKSPACE file it's annoying to roll the change together.
@gregmagolan is about to land the change here to remove Angular from the WORKSPACE file, then we can just let Renovate keep us up-to-date.
