### ISSUE TITLE
Question about output format

### ISSUE THREAD

**Issue by macroorganizm** [angular/angular-bazel-example#289]
Hello, I can't understand, how i can deploy the finished application to some remote env, like heroku. I mean, usually, we have a built application and something like node server to serve it. But how it will look like with Bazel? Structure of output files looks unfitable for regular serving. It means that we need to setup Bazel on the prod environment(in Docker or explicitly), or we able to configure bazel's output, for making it the same form like regular angular's compiler, i mean index.html, bundles(main, vendor etc.) assets and other stuff

**Comment by manekinekko** [comment]
Hi, after you build your app using the `yarn build` command, the bazel will output the bundles under `dist/bin/src` as shown in the following log. So that would be the folder you wanna deploy to prod:

```
$ bazel build //src:bundle
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 1fb139e2-778a-44bf-82fb-17b8bf5914a0
INFO: Analysed target //src:bundle (634 packages loaded, 17121 targets configured).
INFO: Found 1 target...
Target //src:bundle up-to-date:
  dist/bin/src/bundle.es6.js
  dist/bin/src/bundle.js
  dist/bin/src/bundle.min.js
  dist/bin/src/bundle.min_debug.js
  dist/bin/src/bundle.cs.es6
  dist/bin/src/bundle.cs
  dist/bin/src/bundle.cs.min
  dist/bin/src/bundle.cs.min_debug
INFO: Elapsed time: 216.693s, Critical Path: 116.73s
INFO: 65 processes: 4 linux-sandbox, 61 worker.
INFO: Build completed successfully, 788 total actions
Done in 217.04s.
```

**Comment by macroorganizm** [comment]
Yes, but i don't see index.html. Is it not an entry point to the app? Also, we need the index.html file for rendering pages on the server-side using angular universal

**Comment by macroorganizm** [comment]
Looks like prod build more suitable for these goals because prodapp dir looks like:
├── bundle.min.js
├── bundle.min.js.map
├── index.html
└── npm
    └── node_modules
        └── zone.js
            └── dist
                └── zone.min.js
but anyway i'm not sure, that it is a correct way

**Comment by alexeagle** [comment]
There is now a `web_package` rule for this purpose. It writes the `<script>` and `<link>` tags into your `index.html` and the result is a directory that's ready to deploy to production.
We do need examples of how to actually publish the app to a CDN.

**Comment by alexeagle** [comment]
I now added the example of publishing the app to Kubernetes, I hope that answers the question.
