### ISSUE TITLE
Issue compiling with modules in AOT mode

### ISSUE THREAD

**Issue by ewhauser** [angular/angular-bazel-example#291]
I'm running into the dreaded `Function calls are not supported in decorators` with a number of my modules. If I am compiling with the Angular CLI in AOT mode (`ng serve --prod`), I do not get these errors.  I've created a small reproduction here: https://github.com/ewhauser/angular-bazel-example/tree/jwt

```
ERROR: /Users/ewhauser/working/angular-bazel-example/src/BUILD.bazel:14:1: Compiling Angular templates (ngc) //src:src failed (Exit 1)
Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'JwtModule' was called.
: Unexpected value 'undefined' imported by the module 'AppModule in /private/var/tmp/_bazel_ewhauser/77225148e87cf692ce2dde408b0ec7a8/execroot/angular_bazel_example/src/app.module.ts'
Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'JwtModule' was called.
```

**Comment by alexeagle** [comment]
hmm, I suspect that in the CLI we do some different transformation of your sources before handing it to ngc, than what we do under Bazel.

thanks for the repro

**Comment by mgechev** [comment]
@ewhauser with @gregmagolan we worked on a fix. Seems like the problem you reported is no longer reproducible. We hit two other issues, however, that are part of this fix https://github.com/auth0/angular2-jwt/pull/608.

**Comment by mgechev** [comment]
@ewhauser I believe we can close this issue. Please try the latest release of auth0's JWT.
