### ISSUE TITLE
[Question] Why was the angular.json added?

### ISSUE THREAD

**Issue by brannon-darby** [angular/angular-bazel-example#341]
One of the main things I found attractive about the Bazel setup was removal of the bulky angular.json - are there any benefits to maintaining the angular.json with a Bazel setup (besides being able to use `ng xxx` for the commands)?

**Comment by kylecordes** [comment]
Relevant to this... I have worked a bit with two paths to use Bazel:

* with CLI
* instead of CLI

Are there plans to "support" both ways, or just one? To prefer one or the other?

**Comment by kylecordes** [comment]
(From a dependency governance point of view, "instead of CLI" is very appealing. From a convenience-and-features point of view, "with CLI" is great.)

**Comment by alexeagle** [comment]
@brannon-darby it's merely for what you said: able to use e.g. `ng serve` in place of `yarn serve` and so on. We want to demonstrate that using Bazel doesn't mean you have to change your workflow, and with the new Architect API coming in CLI v8, it's trivial for Angular CLI to call Bazel in place of most other work it would do

**Comment by alexeagle** [comment]
@kylecordes we support both ways. You could limit your dependencies somewhat by not installing CLI at all, but I expect most users will continue to use the CLI. Things like `ng lint` are still orthogonal to what Bazel does, and of course for stamping out new modules and components this is still the job of schematics under CLI

**Comment by alexeagle** [comment]
thanks for asking :)
