### ISSUE TITLE
bazel will be default build system of angular-cli in the future？

### ISSUE THREAD

**Issue by Xhhhhhh** [angular/angular-bazel-example#342]
Description:
  hello,everone.The build process of my angular application (build prod ) is slow now, it take over 5-6 minutes.And i want to speed up the build process of my angualr application.I headed bazel's build is fast.So i want to ask bazel will be default build system of angular-cli in the future？if it's, need i migrate my project（a big angular application） build system to bazel currently ? if not ,have any way dealing with the problem of slow build process of current builder of angular-cli ?
  By now , is the one way to speed up build process use high-performance pc?

**Comment by alexeagle** [comment]
I think this is really two different questions.

We're making Bazel an opt-in preview in Angular 8 to get feedback on how it solves problems and what new problems are introduced. If the results are good, we plan to make it the default build for Angular 9. If we do, there's no migration required.

However, you don't need to wait for it to be the default. You can opt-in and use Bazel to break your build into smaller, incremental compilations that can be massively parallelized.
