### ISSUE TITLE
What is the current state of Converting an Angular CLI workspace?

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [angular/angular-bazel-example#407]
What is the upgrade path for Angular 8 and bazel? I read a lot in the changelog about some bazel related changes but is basel the default tool for angular 8?

In the wiki it says "

    In the future, we expect that a command like ng add @angular/bazel will do these steps for you, and you'll only need to interact with the ng command for build, test, serve, etc
"

Can we expect such a feature when 8.0 comes out?

**Comment by alexeagle** [comment]
8.0 is out.
Bazel is an opt-in preview, which means it's still an unstable API (there might be breaking changes) but we encourage you to try it if your build is slow or needs a full-stack multi-lang build.
`ng add @angular/bazel` to an Angular 8 project to convert.
