### ISSUE TITLE
Question: index.html and injected js

### ISSUE THREAD

**Issue by chrislovecnm** [angular/angular-bazel-example#414]
How are the js tags being injected into the primary index.html.  I am upgrading the smaller example we maintain, and I cannot get that working.

**Comment by chrislovecnm** [comment]
The devserver is the only one now that is not updating it.  I can get the prod server to inject the javascript script lines into my index.html

**Comment by gregmagolan** [comment]
If your point the ts_devserver `index_html` attribute to your index.html then ts_devserver should insert any scripts listed in the `assets` attribute via <script> tags. Scripts listed in `scripts` are included in the bundle via concat js but these should be named-UMD or named-AMD. Hope that helps.

**Comment by alexeagle** [comment]
@chrislovecnm we didn't hear back from you so I'll assume your problem was solved?
