### ISSUE TITLE
question: Experimental Support for Ivy in Bazel?

### ISSUE THREAD

**Issue by qzmfranklin** [angular/angular-bazel-example#416]
Just want to understand the feasibility of enabling the experimental Ivy compiler for Angular projects built with the Bazel toolchain.

Have not found anything super useful yet. Most of the stuff I found were related to using Ivy via `ng`, not `bazel`.

Any help is appreciated. Thanks!

**Comment by alexeagle** [comment]
working on it in https://github.com/angular/angular-bazel-example/pull/406
should be quite straightforward as the angular/angular repo uses Bazel to build and test the ivy compiler, but we're missing some config bit somewhere...

**Comment by qzmfranklin** [comment]
Thanks for the good info. I am happy with it and will be waiting for the update. Thanks again.
