### ISSUE TITLE
importHelpers breaks ng test

### ISSUE THREAD

**Issue by saconnolly** [angular/angular-bazel-example#520]
Adding `"importHelpers": true` to the tsconfig causes the tests to fail with the exception `error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.` or `There is no timestamp for tslib.js!`.  ng serve still works as expected

**Comment by alexeagle** [comment]
looks like duplicate of https://github.com/bazelbuild/rules_nodejs/issues/1023
