### ISSUE TITLE
Bazel errors when building targets with rxjs deps

### ISSUE THREAD

**Issue by mikolaj-leszczynski** [angular/angular-bazel-example#522]
When I'm trying to build targets which depends on rxjs lib I'm always getting this kind of error:
```
ERROR: /angular-bazel-example/src/app/billing/module0/BUILD.bazel:26:1: Compiling Angular templates (ngc) //src/app/billing/module0:module0 failed (Exit 1)
src/app/billing/module0/cmp0/cmp0.component.ts(28,3): error TS2742: The inferred type of 'func' cannot be named without a reference to '../../../../../external/npm/node_modules/rxjs/index'. This is likely not portable. A type annotation is necessary.
```
In this case I added `import { of } from 'rxjs'` to `src/app/billing/module0/cmp0.component.ts` and make a fake func in class: `func = () => of(1)`

Of course, I'm adding `@npm//rxjs` to deps of `module0` ng_module. 

This problem is fixed when I add `Observable` to the import statement.

**Comment by alexeagle** [comment]
I think this is reproducible without Bazel - if you have `declarations` enabled in your tsconfig then TS wants a way to reference the inferred type in the resulting .d.ts that describes your public API.
We should document that your code has to work with `declarations` before you migrate to Bazel.

**Comment by mikolaj-leszczynski** [comment]
@alexeagle but I'm not getting this error when I'm building my app without Bazel, only using standard `ng build` with default architect. It's not a problem with my TS then , right ?
